using System.Collections.Generic;
using UnityEngine;

namespace Sapphire
{
    /* Minimal localization: T(english) returns the Korean string when the GAME's language is
       Korean (RDString.language — follows the user's in-game setting), else the English source.
       Keys ARE the English strings, so unmapped text degrades gracefully. Long-form help topics
       are mapped as whole bodies. */
    internal static class Loc
    {
        internal static bool Korean
        {
            get
            {
                try
                {
                    var s = MainClass.Settings;
                    if (s != null && s.UiLanguage == 1) return false;      // forced English
                    if (s != null && s.UiLanguage == 2) return true;       // forced Korean
                    return RDString.language == SystemLanguage.Korean;      // auto: follow the game
                }
                catch { return false; }
            }
        }

        internal static string T(string en)
        {
            if (!Korean || en == null) return en;
            return Ko.TryGetValue(en, out var ko) ? ko : en;
        }

        private static readonly Dictionary<string, string> Ko = new Dictionary<string, string>
        {

            // ── settings panel (Ctrl+E) ──
            ["Features"] = "기능",
            ["FeaturesHelp"] = "기능 그룹을 통째로 켜고 끕니다. 에디터 우측 상단의 마스터 스위치가\n"
                + "이 모두를 함께 제어하며, 여기서는 어떤 그룹을 켤지 고릅니다.",
            ["Event timeline"] = "이벤트 타임라인",
            ["Event panels"] = "이벤트 패널",
            ["Sapphire tools"] = "Sapphire 도구",
            ["MSM & MH tools"] = "MSM · MH 도구",
            ["File menu bar"] = "파일 메뉴 바",
            ["Key hints"] = "단축키 도움말",
            ["Pin event presets"] = "이벤트 프리셋 표시 고정",
            ["Fetching artist list"] = "작곡가 목록 불러오는 중",
            ["Modes"] = "모드",
            ["General"] = "일반",
            ["Quick chart"] = "빠른 차팅",
            ["Quick chart mode"] = "빠른 차팅 모드",
            ["QuickChartHelp"] = "에디터 툴바의 Q 버튼으로 켜는 차팅 모드입니다. 켜져 있는 동안에는 화면을\n"
                + "비우기 위해 이벤트 타임라인이 숨겨지고 아래 단축키가 활성화됩니다.",
            ["I — swirl on/off on the selected tile(s)"] = "I — 선택한 타일의 소용돌이 켜기/끄기",
            ["O — set speed on the selected tile"] = "O — 선택한 타일에 속도 설정",
            ["[ / ] — halve / double that tile's speed"] = "[ / ] — 해당 타일 속도를 절반 / 두 배로",
            ["Shift+P — Pause event (prompts for beats)"] = "Shift+P — 정지 이벤트 (박자를 입력받습니다)",
            ["Shift+L — tile-location event (prompts X / Y)"] = "Shift+L — 타일 위치 이벤트 (X / Y를 입력받습니다)",
            ["Shift+G — angle pad: space-separated RELATIVE angles (180 = straight; math ok), Place a whole run"]
                = "Shift+G — 각 패드: 공백으로 구분한 상대 각도를 입력해 (180 = 직진, 수식 가능) 한 번에 배치합니다",
            ["These keys never clash with the game's tile placement."]
                = "이 키들은 게임의 타일 배치 키와 절대 겹치지 않습니다",
            ["Editor mode"] = "에디터 모드",
            ["EditorModeHelp1"] = "차팅을 위한 깨끗한 화면입니다. 에디터에 있는 동안(플레이 테스트 포함)\n"
                + "Sapphire 오버레이와 키 뷰어가 물러나고, 게임의 난이도·노페일·자동플레이\n"
                + "아이콘과 자동플레이 문구, 판정 오차 미터가 숨겨집니다.",
            ["EditorModeHelp2"] = "설정은 하나도 바뀌지 않습니다. 에디터를 나가거나 이 항목을 끄면\n"
                + "모두 원래대로 돌아옵니다.",
            ["Autoplay pause"] = "자동플레이 일시정지",
            ["Enable autoplay pause"] = "자동플레이 일시정지 사용",
            ["AutoplayHelp"] = "에디터에서 플레이 테스트하는 동안 자동플레이를 멈추고 다시 재생합니다\n"
                + "(게임은 Space로 고정되어 있습니다). 버튼을 누른 뒤 원하는 키를 눌러 바꿉니다.",
            ["Press a key…"] = "키를 누르세요…",
            ["Pause key"] = "일시정지 키",
            ["Language"] = "언어",
            ["Keybinds"] = "단축키",
            ["Keep panel layout after restart"] = "재시작 후에도 패널 배치 유지",
            ["PanelLayoutHelp"] = "패널의 열림/닫힘 상태와 위치는 한 세션 동안 그대로 유지됩니다.\n"
                + "이 옵션을 켜면 게임을 다시 켜도 그대로 복원되고, 꺼두면 실행할 때마다 초기화됩니다.",
            // Hz tool
            ["Hz tool"] = "Hz 도구",
            ["Shape BPM"] = "도형 BPM",
            ["Actual Hz"] = "실제 Hz",
            ["Suggest sides & laps"] = "변 수·바퀴 수 추천",
            ["suggested"] = "추천:",
            ["ideal"] = "이상값",
            [" cents"] = " 센트",
            ["duration is exact; the tile count is whole, so the pitch snaps"] = "길이는 정확히 맞추고, 타일 수가 정수라 음높이가 그 값에 맞춰집니다",
            ["Base BPM"] = "기준 BPM",
            ["SetSpeed"] = "속도 변경",
            ["shape BPM = angle × Hz ÷ 3 · lock one, edit another"] = "도형 BPM = 각도 × Hz ÷ 3 · 하나를 잠그고 다른 값을 바꾸세요",
            ["Follow selected tile"] = "선택한 타일 따라가기",
            ["Frequency (Hz)"] = "주파수 (Hz)",
            ["Hits / minute"] = "분당 타수",
            ["Tile angle"] = "타일 각도",
            ["angle = 180 × BPM ÷ (Hz × 60)"] = "각도 = 180 × BPM ÷ (Hz × 60)",
            ["Note"] = "음",
            ["To angle pad"] = "각 패드로 보내기",
            ["Tuning"] = "음률",
            ["EDO (steps / octave)"] = "EDO (옥타브당 단계)",
            ["Reference pitch (Hz)"] = "기준 음높이 (Hz)",
            ["Use this tile's BPM"] = "이 타일의 BPM 사용",
            ["Duration (beats)"] = "길이 (박자)",
            ["Full circle"] = "완전한 원",
            ["Perfect circles"] = "완전히 닫힌 원",
            ["Exact pitch (pad with a pause)"] = "정확한 음높이 (정지로 채우기)",
            ["Pause"] = "정지",
            ["pause"] = "정지",
            ["beats"] = "박자",
            ["run"] = "묶음",
            ["the arc stops where the pitch is closest; only the curvature is kept"] = "곡률만 유지한 채, 음높이가 가장 가까운 지점에서 호가 끝납니다",
            ["Laps"] = "바퀴 수",
            [" speed"] = " 속도",
            ["already at this BPM"] = "이미 이 BPM입니다",
            ["Sides"] = "변 수",
            ["a closed loop needs angle = 180 − 360 ÷ sides, so the Hz snaps"] = "닫힌 고리는 각도 = 180 − 360 ÷ 변 수가 되어야 하므로 Hz가 그 값에 맞춰집니다",
            ["Write SetSpeed for this BPM"] = "이 BPM에 맞춰 SetSpeed 작성",
            ["angle = 180 × BPM ÷ (Hz × 60) · lock one, edit another"] = "각도 = 180 × BPM ÷ (Hz × 60) · 하나를 잠그고 다른 값을 바꾸세요",
            ["Reference octave"] = "기준 옥타브",
            ["Reference step"] = "기준 단계",
            ["Reset tuning"] = "음률 초기화",
            ["12-EDO · step 9 · octave 4 · 440 Hz = concert A"] = "12-EDO · 9단계 · 4옥타브 · 440 Hz = 표준 A",
            ["Set a BPM and a frequency first"] = "BPM과 주파수를 먼저 입력하세요",
            ["sent to the angle pad"] = "각 패드로 보냈습니다",
            // angle pad → shape library
            ["Store as shape"] = "도형으로 저장",
            ["Add to Shape Library"] = "도형 라이브러리에 추가",
            ["append t for twirl · math supported · (…)*n"] = "t를 붙이면 소용돌이 · 수식 지원 · (…)*n",
            ["run too long to store"] = "저장하기에 너무 긴 묶음입니다",
            ["stored in"] = "저장 위치:",
            ["Non-repeating shapes"] = "반복 없는 도형",
            ["KeybindsHelp"] = "단축키를 눌러 다시 지정합니다. 누른 순간의 Shift 상태가 함께 저장되므로\n"
                + "Shift+G는 Shift+G로, 그냥 G는 G로 지정됩니다.\n"
                + "게임 에디터는 타일 배치 키 17개(a b c d e h j m n q s t v w x y z)를 Shift 유무\n"
                + "양쪽에 모두 등록하므로, 그 글자들은 Shift를 붙여도 충돌합니다. 기본값은 충돌하지\n"
                + "않는 키(f g i k l o p r u)만 사용합니다.",
            ["Reset all keybinds"] = "모든 단축키 초기화",
            ["Tools"] = "도구",
            ["also"] = "중복:",
            ["Halve speed"] = "속도 절반",
            ["Double speed"] = "속도 두 배",
            ["LanguageHelp"] = "Sapphire 에디터 UI와 도움말의 언어입니다. 자동은 게임 설정을 따릅니다.",
            ["Auto (follow game)"] = "자동 (게임 설정)",
            ["English"] = "English",
            ["Invert scroll direction"] = "스크롤 방향 반전",
            ["Updates"] = "업데이트",
            ["UpdatesHelp"] = "Sapphire는 세션마다 한 번 GitHub 릴리스를 확인하고, 더 새로운 빌드가 있으면\n"
                + "토스트를 띄웁니다. 토스트를 누르면 내려받아 이 사본 위에 설치하며, 새 버전은\n"
                + "게임을 다시 시작한 뒤 적용됩니다. 내려받은 파일은 GitHub가 게시한 체크섬으로\n"
                + "검증합니다.",
            ["Installed"] = "설치됨",
            ["Check for updates automatically"] = "업데이트 자동 확인",
            ["Include pre-release builds"] = "시험판 빌드 포함",
            ["Check now"] = "지금 확인",
            ["Un-skip"] = "건너뛰기 해제",
            ["Checking…"] = "확인 중…",
            ["Up to date"] = "최신 버전입니다",
            ["Available"] = "새 버전",
            ["Downloading…"] = "내려받는 중…",
            ["Installed — restart the game to apply"] = "설치됨 — 게임을 다시 시작하면 적용됩니다",
            ["Failed"] = "실패",
            ["Not checked yet"] = "아직 확인하지 않음",
            // ── toolbar tooltips / tool names ──
            ["Circular path"] = "원형 경로",
            ["Free angle"] = "자유 각도",
            ["Pseudo"] = "동타",
            ["Camera path"] = "카메라 경로",
            ["VFX preview (ESC exits)"] = "VFX 미리보기 (ESC로 종료)",
            ["Inspector (copy tile events)"] = "인스펙터 (타일 이벤트 복사)",
            ["Zip Tool"] = "드르륵",
            ["Instruction manual"] = "설명",
            ["Zip"] = "드르륵",
            ["Inspector"] = "인스펙터",
            ["Inspector · pick a tile"] = "인스펙터 · 타일을 선택하세요",

            // ── submenus ──
            ["Keys"] = "키 수",
            ["Midspin"] = "미드스핀",
            ["Angle"] = "각도",
            ["Custom"] = "커스텀",
            ["Beats"] = "박자",
            ["per-tile angles, e.g. 30 60 90"] = "타일별 각도, 예: 30 60 90",
            ["▶ Play all"] = "▶ 전체 재생",
            ["▶ Selected"] = "▶ 선택부터",
            ["Play Gaps"] = "박자 간격 재생",

            // ── curved path dialog ──
            ["Curved path"] = "곡선 경로",
            ["Pseudo (star)"] = "동타 (별)",
            ["Pseudo per round"] = "한 바퀴당 동타",
            ["Pseudo angle"] = "동타 각도",
            ["Reverse"] = "반전",
            ["Outer angle"] = "외각",
            ["Inner angle"] = "내각",
            ["Keep BPM"] = "BPM 유지",
            ["Pseudos as mid-spin tiles"] = "동타를 미드스핀 타일로",
            ["Circle degrees"] = "원 각도",
            ["Tile count"] = "타일 수",

            // ── batch dialog ──
            ["Pseudo interval"] = "동타 간격",
            ["Pseudo across {0} tiles"] = "타일 {0}개에 동타",
            ["Angled at {0}° (inline needs 90°)."] = "{0}° 각도 (인라인은 90°에서만 가능).",
            ["Set pseudos to {0}°"] = "동타를 {0}°로 변경",
            ["Level settings"] = "레벨 설정",
            ["On"] = "켬",
            // filter manager: keys/values the game leaves unmapped in its own tables
            ["targetType"] = "대상 유형",
            ["Foreground"] = "전경",
            ["Background"] = "배경",
            ["(no events on this tile)"] = "(이 타일에 이벤트 없음)",
            ["(settings unavailable)"] = "(설정을 불러올 수 없음)",
            ["Search events"] = "이벤트 검색",
            ["Favorites"] = "즐겨찾기",
            ["Style"] = "스타일",
            ["Upwards"] = "위로",
            ["Sideways"] = "옆으로",
            ["Inline"] = "인라인",
            ["Downwards"] = "아래로",
            ["Apply"] = "적용",
            ["Style: Inline (selection isn't straight)"] = "스타일: 인라인 (선택이 직선이 아님)",

            // ── tile menu ──
            ["Copy"] = "복사",
            ["Cut"] = "잘라내기",
            ["Paste"] = "붙여넣기",
            ["Delete"] = "삭제",
            ["Rotate CW"] = "시계 방향 회전",
            ["Rotate CCW"] = "반시계 방향 회전",

            // ── copy / mirror panel ──
            ["Copy options"] = "복사 옵션",
            ["Mirror"] = "반전",
            ["Horizontal"] = "좌우",
            ["Vertical"] = "상하",
            ["Preserve beats"] = "박자 유지",
            ["Events"] = "이벤트",
            ["All"] = "전체",
            ["None"] = "없음",
            ["Paste filter"] = "붙여넣기 필터",

            // ── bulk edit / batch event actions ──
            ["Bulk edit"] = "일괄 편집",
            ["matching events"] = "개 이벤트 일치",
            ["field(s) set"] = "개 항목 지정됨",
            ["Tag filter (blank = all)"] = "태그 필터 (비우면 전체)",
            ["Apply to"] = "적용 대상",
            ["Reset fields"] = "항목 초기화",
            ["events"] = "개 이벤트",
            ["selected"] = "개 선택됨",
            ["Delete all events"] = "모든 이벤트 삭제",
            ["Delete all events on this tile?"] = "이 타일의 모든 이벤트를 삭제할까요?",
            ["Delete selected events?"] = "선택한 이벤트를 삭제할까요?",
            ["Delete this event group?"] = "이 이벤트 그룹을 삭제할까요?",
            ["Nothing to apply — change a field first, or widen the tag filter."]
                = "적용할 항목이 없습니다 — 값을 먼저 바꾸거나 태그 필터를 넓히세요.",
            ["OK"] = "확인",
            ["Event save inspired by EditorCustomModules"] = "이벤트 저장 기능은 EditorCustomModules에서 영감을 받았습니다",
            ["(no events)"] = "(이벤트 없음)",
            ["Gameplay"] = "게임플레이",
            ["Track"] = "트랙",
            ["Decorations"] = "장식",
            ["VFX"] = "시각 효과",
            ["Modifiers"] = "수정",
            ["Conveniences"] = "편의 기능",
            ["DLC"] = "DLC",
            ["Other"] = "그 외",

            // ── presets ──
            ["Presets"] = "프리셋",
            ["Preset"] = "프리셋",
            ["+ Save capture"] = "+ 캡처 저장",
            ["(none — capture a tile, then Save)"] = "(없음 — 타일을 캡처한 뒤 저장하세요)",

            // ── camera timeline ──
            ["Ease"] = "가감속",
            ["Custom bezier"] = "커스텀 베지어",
            ["Graph"] = "그래프",
            ["Graph View"] = "그래프",
            ["Filters…"] = "필터 관리…",
            ["Filter manager"] = "필터 관리자",
            ["Filter manager (legacy)"] = "필터 관리자 (레거시)",
            ["Delete event"] = "이벤트 삭제",
            ["(no filter events on this tile)"] = "(이 타일에 필터 이벤트 없음)",
            ["Edited in the event panel"] = "이벤트 패널에서 편집하세요",
            ["Search filters"] = "필터 검색",
            ["All"] = "전체",
            ["Needs an earlier keyframe for the start value"] = "시작 값을 읽을 이전 키프레임이 필요합니다",
            ["This keyframe has no duration to decompose"] = "분해할 지속 시간이 없는 키프레임입니다",
            ["This keyframe animates nothing decomposable"] = "분해할 수 있는 속성이 없는 키프레임입니다",
            ["Segments"] = "구간 수",
            ["Cancel"] = "취소",
            ["Position"] = "위치",
            ["Rotation"] = "회전",
            ["Zoom"] = "확대",

            // ── magic shape panel ──
            ["Magic Shape"] = "마법진",
            ["Magic shape (multiply / create / rotate)"] = "마법진 (승수 / 생성 / 회전)",
            ["Multiply"] = "승수",
            ["Create"] = "생성",
            ["Rotate"] = "회전",
            ["Target BPM"] = "목표 BPM",
            ["Multiplier"] = "배수",
            ["BPM"] = "BPM",
            ["Write as"] = "기록 방식",
            ["Twirls"] = "회오리",
            ["Keep"] = "유지",
            ["Strip"] = "제거",
            ["Inner"] = "내각",
            ["Outer"] = "외각",
            ["Top icon"] = "상단 아이콘",
            ["Speed"] = "속도",
            ["Twirl"] = "회오리",
            ["Reshape angles instead"] = "각도 재구성 모드",
            ["Angle fix"] = "각도 보정",
            ["Off"] = "끔",
            ["Apply to selection"] = "선택 영역에 적용",
            ["Tiles"] = "타일",
            ["Sel"] = "선택",
            ["Vertices"] = "꼭짓점",
            ["Inverse direction"] = "반대 방향",
            ["Preview (ghost tiles)"] = "미리보기 (고스트 타일)",
            ["Create shape"] = "마법진 생성",
            ["Degrees"] = "각도(°)",
            ["Rotate range"] = "범위 회전",
            ["Applied"] = "적용됨",
            ["Shape created"] = "마법진 생성됨",
            ["Select at least two tiles"] = "타일을 2개 이상 선택하세요",
            ["Nothing selected"] = "선택된 타일이 없습니다",
            ["Range contains unsupported events: {0}"] = "범위에 지원되지 않는 이벤트가 있습니다: {0}",
            ["Angle exceeds 360° at tile {0} — set Angle fix"] = "타일 {0}에서 각도가 360°를 초과합니다 — 각도 보정을 설정하세요",
            ["Tile {0}: old levels need 15° multiples"] = "타일 {0}: 구버전 레벨은 15° 배수만 가능합니다",
            ["Needs a modern (mesh-floor) level"] = "신버전 (메시 타일) 레벨이 필요합니다",
            ["Vertices must be at least 2"] = "꼭짓점은 2개 이상이어야 합니다",
            ["Multiply failed — see log"] = "승수 적용 실패 — 로그를 확인하세요",
            ["Create failed — see log"] = "생성 실패 — 로그를 확인하세요",
            ["Rotate failed — see log"] = "회전 실패 — 로그를 확인하세요",

            // ── track tools panel ──
            ["Track Tools"] = "트랙 도구",
            ["Track tools (fades / explode / copies / generate)"] = "트랙 도구 (페이드 / 폭발 / 복제 / 생성)",
            ["Fade in"] = "페이드 인",
            ["Fade out"] = "페이드 아웃",
            ["Explode"] = "폭발",
            ["Size"] = "크기",
            ["Multi"] = "다중 트랙",
            ["Generate"] = "생성",
            ["Move window"] = "이동 범위 (상대)",
            ["Window (rel)"] = "범위 (상대)",
            ["Duration"] = "지속 시간",
            ["Duration follows BPM"] = "지속 시간 BPM 연동",
            ["X offset"] = "X 오프셋",
            ["Y offset"] = "Y 오프셋",
            ["Rotation"] = "회전",
            ["Scale"] = "크기",
            ["Opacity"] = "불투명도",
            ["Land scale"] = "도착 크기",
            ["Land parallax"] = "도착 시차",
            ["Angle offset"] = "각도 오프셋",
            ["Step angle"] = "단계별 각도",
            ["Track scale"] = "트랙 크기",
            ["Radius"] = "반지름",
            ["Planets"] = "행성",
            ["Copies"] = "복제",
            ["Animate"] = "애니메이션",
            ["Per tile"] = "타일별",
            ["One tile"] = "한 타일에",
            ["Tag"] = "태그",
            ["Fake planets"] = "가짜 행성",
            ["Planet events on first tile"] = "행성 이벤트를 첫 타일에",
            ["Depth 1st/step"] = "깊이 시작/증가",
            ["Parallax"] = "시차",
            ["Parallax affects planets"] = "시차를 행성에도 적용",
            ["Appear"] = "등장",
            ["Disappear"] = "소멸",
            ["Events per tile (off: first tile)"] = "이벤트 타일별 (끄면 첫 타일)",
            ["Copy # offset"] = "복제 번호 오프셋",
            ["Create copies"] = "복제 생성",
            ["Enter the copies' tag first"] = "먼저 복제 태그를 입력하세요",
            ["After tile"] = "타일 뒤에",
            ["End"] = "끝",
            ["Angles (T = twirl)"] = "각도 목록 (T = 회오리)",
            ["Repeat"] = "반복",
            ["Added {0} tiles"] = "타일 {0}개 추가됨",
            ["No angles parsed — e.g. 45 90T 135"] = "각도를 읽지 못했습니다 — 예: 45 90T 135",
            ["{0} failed — see log"] = "{0} 실패 — 로그를 확인하세요",
            ["Multi-track"] = "다중 트랙",
            ["Animate copies"] = "복제 애니메이션",

            // ── deco tools panel ──
            ["Deco Tools"] = "장식 도구",
            ["Deco tools (flipbook / video / 3D / lyrics)"] = "장식 도구 (플립북 / 영상 / 3D / 가사)",
            ["Flipbook"] = "플립북",
            ["Extract"] = "추출",
            ["3D stack"] = "3D 스택",
            ["Lyrics"] = "가사",
            ["Frame folder"] = "프레임 폴더",
            ["Event tag"] = "이벤트 태그",
            ["Frame window (off: all frames)"] = "프레임 범위 (끄면 전체)",
            ["Frames"] = "프레임",
            ["Start angle"] = "시작 각도",
            ["Angle per frame"] = "프레임당 각도",
            ["Create flipbook"] = "플립북 생성",
            ["{0} frames per tile"] = "타일당 프레임 {0}개",
            ["No frames found"] = "프레임을 찾지 못했습니다",
            ["Frame folder not found in the level folder"] = "레벨 폴더에서 프레임 폴더를 찾지 못했습니다",
            ["Video file (in the level folder)"] = "영상 파일 (레벨 폴더 안)",
            ["Format"] = "형식",
            ["Extract frames"] = "프레임 추출",
            ["Already extracting…"] = "이미 추출 중입니다…",
            ["Extracting frames…"] = "프레임 추출 중…",
            ["Extracted {0} frames to {1}"] = "{1} 폴더에 프레임 {0}개 추출됨",
            ["Video file not found"] = "영상 파일을 찾지 못했습니다",
            ["Frames land in a folder named after the video — use it in Flipbook."] = "프레임은 영상 이름의 폴더에 저장됩니다 — 플립북에서 사용하세요.",
            ["Image file"] = "이미지 파일",
            ["Image file not found"] = "이미지 파일을 찾지 못했습니다",
            ["Pos X from/to"] = "위치 X 시작/끝",
            ["Pos Y from/to"] = "위치 Y 시작/끝",
            ["Pivot X from/to"] = "피벗 X 시작/끝",
            ["Pivot Y from/to"] = "피벗 Y 시작/끝",
            ["Rotation from/to"] = "회전 시작/끝",
            ["Scale X from/to"] = "크기 X 시작/끝",
            ["Scale Y from/to"] = "크기 Y 시작/끝",
            ["Opacity from/to"] = "불투명도 시작/끝",
            ["Depth from/to"] = "깊이 시작/끝",
            ["Parallax X f/t"] = "시차 X 시작/끝",
            ["Parallax Y f/t"] = "시차 Y 시작/끝",
            ["Color from/to"] = "색상 시작/끝",
            ["Create stack"] = "스택 생성",
            ["Lyric text"] = "가사 텍스트",
            ["Split"] = "분할",
            ["Words"] = "단어별",
            ["Chars"] = "글자별",
            ["Generate"] = "생성",
            ["All parts"] = "전체",
            ["First only"] = "첫 부분만",
            ["As"] = "생성 방식",
            ["Game text"] = "게임 텍스트",
            ["PNG (font)"] = "PNG (폰트)",
            ["Color (hex)"] = "색상 (hex)",
            ["Spacing X/Y"] = "간격 X/Y",
            ["Part stagger (°)"] = "부분별 지연 (°)",
            ["Pivot X"] = "피벗 X",
            ["Pivot Y"] = "피벗 Y",
            ["PNG rendering"] = "PNG 렌더링",
            ["Font file"] = "폰트 파일",
            ["Stroke size"] = "외곽선 크기",
            ["Stroke color"] = "외곽선 색상",
            ["Shadow spread"] = "그림자 퍼짐",
            ["Shadow offset"] = "그림자 오프셋",
            ["Shadow density"] = "그림자 농도",
            ["Shadow color"] = "그림자 색상",
            ["Disappear animation"] = "소멸 애니메이션",
            ["After (beats)"] = "지연 (박자)",
            ["Generate lyrics"] = "가사 생성",
            ["Generated {0} lyric parts"] = "가사 {0}부분 생성됨",
            ["Enter a tag first"] = "먼저 태그를 입력하세요",
            ["Enter the lyric text"] = "가사 텍스트를 입력하세요",
            ["Save the level first"] = "먼저 레벨을 저장하세요",
            ["Font file (.ttf/.otf) not found"] = "폰트 파일(.ttf/.otf)을 찾지 못했습니다",
            ["Lyric contains characters invalid in file names"] = "가사에 파일 이름으로 쓸 수 없는 문자가 있습니다",

            // ── pitch bar ──
            ["Pitch"] = "피치",
            ["Reset"] = "초기화",

            // ── help mode chrome ──
            ["× Exit"] = "× 닫기",
            ["Help"] = "도움말",
            ["Help mode"] = "도움말 모드",

            // ── shape library ──
            ["Shape library"] = "도형 라이브러리",
            ["Insert"] = "삽입",
            ["New shape"] = "새 도형",
            ["From selection"] = "선택에서 가져오기",
            ["Name"] = "이름",
            ["Category"] = "분류",
            ["Angles"] = "각도",
            ["+ Category"] = "+ 분류",
            ["+ Shape"] = "+ 도형",
            ["Delete category"] = "분류 삭제",
            ["Delete shape"] = "도형 삭제",
            ["(its shapes are removed too)"] = "(포함된 도형도 삭제됩니다)",
            ["select a run of tiles first"] = "먼저 타일을 선택하세요",
            [" tiles captured"] = " 타일 캡처됨",
            ["check the angles"] = "각도를 확인하세요",
            ["e.g. 30t 30t 180  (t = twirl · sum = base)"] = "예: 30t 30t 180  (t = 회전 · 합 = 기준각)",

            // ── quick chart / angle pad ──
            ["Quickchart Mode"] = "퀵차트 모드",
            ["Angle pad"] = "각도 패드",
            ["Set speed"] = "속도 설정",
            ["Place"] = "배치",
            ["Duplicate"] = "복제",
            ["+ Decoration"] = "+ 장식",
            ["Decoration"] = "장식",
            ["(no decorations)"] = "(장식 없음)",
            ["(untagged)"] = "(태그 없음)",
            ["View: List"] = "보기: 목록",
            ["View: Grid (thumbnails)"] = "보기: 그리드 (썸네일)",
            ["image"] = "이미지",
            ["text"] = "텍스트",
            ["object"] = "오브젝트",
            ["particle"] = "파티클",
            ["component"] = "컴포넌트",
            ["Artist permission"] = "아티스트 허가",
            // ── updater ──
            ["Update available"] = "업데이트 있음",
            ["Click to update"] = "클릭해서 업데이트",
            ["Downloading update…"] = "업데이트 다운로드 중…",
            ["Please wait"] = "잠시만 기다려 주세요",
            ["Update installed"] = "업데이트 설치됨",
            ["Restart the game to apply it"] = "게임을 재시작하면 적용됩니다",
            ["Update failed"] = "업데이트 실패",
            ["GitHub rate limit — try again later"] = "GitHub 요청 제한 — 나중에 다시 시도하세요",
            ["Release feed not found"] = "릴리스 목록을 찾을 수 없음",
            ["No connection"] = "연결할 수 없음",

            ["Close"] = "닫기",
            ["check the expression"] = "식을 확인하세요",
            ["check the value"] = "값을 확인하세요",
            ["check "] = "확인: ",
            ["select a tile / open a level"] = "타일 선택 / 레벨 열기",
            ["select a tile first"] = "먼저 타일을 선택하세요",
            [" tile"] = " 타일",
            [" placed"] = " 배치됨",
            ["Colour stops"] = "색상 지점",
            ["Alpha stops"] = "투명도 지점",
            ["Particle preview"] = "입자 미리보기",
            ["Play"] = "재생",
            ["Stop"] = "정지",
            ["Restart"] = "다시 시작",

            // ── on-screen key hints card ──
            // Own key, NOT the existing "Keys" (that one means "key count" for pseudo/zip tools) —
            // this card's header means "shortcuts" and the two must not share a Loc entry.
            ["On-screen key hints"] = "화면 단축키 도움말",
            ["Sapphire settings"] = "Sapphire 설정",
            ["Close panel / disarm tool"] = "패널 닫기 / 도구 해제",
            ["Select tool"] = "도구 선택",
            ["Pan camera"] = "카메라 이동",
            ["Add/remove event row"] = "이벤트 행 추가/제거",
            ["Select event range"] = "이벤트 범위 선택",
            ["Previous tool"] = "이전 도구",
            ["Saved tool slot"] = "저장한 도구 슬롯",
            ["Save current tool to slot"] = "현재 도구를 슬롯에 저장",
            ["Hold: free-angle aim"] = "누르는 동안 자유 각도 조준",
            ["Set key count"] = "키 수 설정",
            ["Swirl on/off"] = "소용돌이 켜기/끄기",
            ["Halve / double speed"] = "속도 절반 / 두 배",
            ["Pause event"] = "정지 이벤트",
            ["Tile location event"] = "타일 위치 이벤트",
        };

        // Help topics: whole bodies mapped EN→KO (fallback = English). Kept beside the short
        // strings so the tables stay in one reviewable place.
        internal static string Body(string en) => T(en);
    }
}
